---
# tasks file for s3fs-mount
- name: ensure s3fs is installed
  apt: name=s3fs state=present

- name: ensure password file for s3fs is correct
  template:
    src: ./templates/s3fs-password.j2
    dest: '{{ ansible_env.HOME }}/s3fs-password'
    mode: '600'

- include: mount-s3fs.yml mount_args={{ item }}
  loop: '{{ s3fs_mounts }}'
